services:
  ycsb:
    container_name: ycsb
    image: quay.io/aviana/ycsb_jdbc:1.0.17
    environment:
      - WORKLOAD_FILENAME=<workload_to_run>
      - CONFIG_FILENAME=mysql.properties
      - TABLE_NAME=<tables_to_use>
      - NUM_PROCESSES=<num_processes>
      # - TOTAL_RECORDS=10000000
      - MAX_THROUGHPUT=<desired_throughput>
      - DEBUG=false
    volumes:
      - ./ycsb_config/conf:/ycsb/conf
      - ./ycsb_config/results:/ycsb/results
      - ../workloads:/ycsb/workloads

