services:
  ycsb:
    container_name: ycsb
    image: quay.io/aviana/ycsb_jdbc:1.0.17
    environment:
      - WORKLOAD_FILENAME=5t_10kr_05i_05u
      - CONFIG_FILENAME=mysql.properties
      - TABLE_NAME=usertable_0,usertable_1,usertable_2,usertable_3,usertable_4,usertable_5,usertable_6,usertable_7,usertable_8,usertable_9
      - NUM_PROCESSES=5
      - TOTAL_RECORDS=100000000
      - MAX_THROUGHPUT=1000
      - DEBUG=false
    volumes:
      - ./ycsb_config/conf:/ycsb/conf
      - ./ycsb_config/results:/ycsb/results
      - ../workloads:/ycsb/workloads

