{
 "title": "MongoDB Debezium Server Streaming",
 "tags": [
  "debezium-server",
  "streaming",
  "mongodb"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total throughput (msg/s)",
   "type": "timeseries",
   "description": "Overall messages being produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(debezium_metrics_TotalNumberOfCreateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "Create Events"
    },
    {
     "expr": "rate(debezium_metrics_TotalNumberOfUpdateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "Update Events"
    },
    {
     "expr": "rate(debezium_metrics_TotalNumberOfDeleteEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "DeleteEvents"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "timeseries",
   "description": "Show the memory used by the debezium container. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\",name=\"debezium\"} / (1024 * 1024)",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "MongoDB throughput (msg/s)",
   "type": "timeseries",
   "description": "MySQL command performed (insert, update, delete)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{job=\"mongodb\",type=\"insert\"}[$__rate_interval])",
     "legendFormat": "Create"
    },
    {
     "expr": "rate(mongodb_op_counters_total{job=\"mongodb\",type=\"update\"}[$__rate_interval])",
     "legendFormat": "Update"
    },
    {
     "expr": "rate(mongodb_op_counters_total{job=\"mongodb\",type=\"delete\"}[$__rate_interval])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Calculated Container CPU usage (4 vCPUs)",
   "type": "timeseries",
   "description": "Calculated CPU usage for a machine with 4 vCPUs. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{job=\"cadvisor\",name=\"debezium\"}[5m]) / 4",
     "legendFormat": "Container CPU Usage (%)"
    }
   ]
  },
  {
   "title": "MongoDB bottlenecks",
   "type": "timeseries",
   "description": "Show MongoDB bottlenecks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_latencies_latency_total{job=\"mongodb\"}[$__rate_interval])) / 1000",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "Container Network I/O",
   "type": "timeseries",
   "description": "Network usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])",
     "legendFormat": "Network Received Bytes"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])",
     "legendFormat": "Network Transmitted Bytes"
    }
   ]
  },
  {
   "title": "Send failures/errors",
   "type": "timeseries",
   "description": "Track if any messages are being dropped.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_metrics_record_error{job=\"debezium\"}[$__rate_interval]))\n",
     "legendFormat": "Error sumatory"
    }
   ]
  },
  {
   "title": "Container Disk I/O",
   "type": "timeseries",
   "description": "Disk usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])",
     "legendFormat": "Disk Read Bytes"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])",
     "legendFormat": "Disk Writes Bytes"
    }
   ]
  }
 ]
}