{
 "title": "MySQL Debezium Server Streaming",
 "tags": [
  "debezium-server",
  "streaming",
  "mysql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Elapsed time (hours)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$__range_s / 3600 ", "legendFormat": "Hours passed" }
   ]
  },
  {
   "title": "Total throughput (msg/s)",
   "type": "timeseries",
   "description": "Overall messages being produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(debezium_metrics_TotalNumberOfCreateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "Create Events"
    },
    {
     "expr": "rate(debezium_metrics_TotalNumberOfUpdateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "Update Events"
    },
    {
     "expr": "rate(debezium_metrics_TotalNumberOfDeleteEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])",
     "legendFormat": "DeleteEvents"
    }
   ]
  },
  {
   "title": "Total throughput (msg/s)",
   "type": "stat",
   "description": "Overall messages being produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rate(debezium_metrics_TotalNumberOfCreateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Create Events"
    },
    {
     "expr": "avg_over_time(rate(debezium_metrics_TotalNumberOfUpdateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Update Events"
    },
    {
     "expr": "avg_over_time(rate(debezium_metrics_TotalNumberOfDeleteEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:])",
     "legendFormat": "DeleteEvents"
    }
   ]
  },
  {
   "title": "Queue Capacity",
   "type": "timeseries",
   "description": "Overall messages being produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\"}",
     "legendFormat": "Remaining Queue Capacity"
    },
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\"}",
     "legendFormat": "Total Queue Capacity"
    }
   ]
  },
  {
   "title": "Total throughput (msg/s)",
   "type": "stat",
   "description": "Overall messages being produced per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rate(debezium_metrics_TotalNumberOfCreateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:]) +\navg_over_time(rate(debezium_metrics_TotalNumberOfUpdateEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:]) +\navg_over_time(rate(debezium_metrics_TotalNumberOfDeleteEventsSeen{context=\"streaming\", job=\"debezium\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Total Number Of Events"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "timeseries",
   "description": "Show the memory used by the debezium container. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\",name=\"debezium\"} / (1024 * 1024)",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "stat",
   "description": "Show the memory used by the debezium container. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((container_memory_usage_bytes{job=\"cadvisor\", name=\"debezium\"} / (1024 * 1024))[$__range:])\n",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Calculated Container CPU usage (4 vCPUs)",
   "type": "timeseries",
   "description": "Calculated CPU usage for a machine with 4 vCPUs. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{job=\"cadvisor\",name=\"debezium\"}[5m]) / 4",
     "legendFormat": "Container CPU Usage (%)"
    }
   ]
  },
  {
   "title": "Calculated Container CPU usage (4 vCPUs)",
   "type": "stat",
   "description": "Calculated CPU usage for a machine with 4 vCPUs. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((100 * rate(container_cpu_usage_seconds_total{job=\"cadvisor\", name=\"debezium\"}[5m]) / 4)[$__range:])",
     "legendFormat": "Container CPU Usage (%)"
    }
   ]
  },
  {
   "title": "Container Network I/O",
   "type": "timeseries",
   "description": "Network usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])",
     "legendFormat": "Network Received Bytes"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])",
     "legendFormat": "Network Transmitted Bytes"
    }
   ]
  },
  {
   "title": "Container Network I/O",
   "type": "stat",
   "description": "Network usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rate(container_network_receive_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])[$__range:])/1024",
     "legendFormat": "Network Received MB"
    },
    {
     "expr": "avg_over_time(rate(container_network_transmit_bytes_total{job=\"cadvisor\",name=\"debezium\"}[$__interval])[$__range:])/1024",
     "legendFormat": "Network Transmitted MB"
    }
   ]
  },
  {
   "title": "Container Disk I/O",
   "type": "timeseries",
   "description": "Disk usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])",
     "legendFormat": "Disk Read Bytes"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])",
     "legendFormat": "Disk Writes Bytes"
    }
   ]
  },
  {
   "title": "Container Disk I/O",
   "type": "stat",
   "description": "Disk usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rate(container_fs_reads_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])[$__range:])/1024",
     "legendFormat": "Disk Read MB"
    },
    {
     "expr": "avg_over_time(rate(container_fs_writes_bytes_total{job=\"cadvisor\", name=\"debezium\"}[$__interval])[$__range:])/1024",
     "legendFormat": "Disk Writes MB"
    }
   ]
  },
  {
   "title": "MySQL throughput (msg/s)",
   "type": "timeseries",
   "description": "MySQL command performed (insert, update, delete)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\",command=\"select\"}[$__rate_interval])",
     "legendFormat": "Read Operation Rate"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\",command=\"insert\"}[$__rate_interval])",
     "legendFormat": "Insert Operation Rate"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\",command=\"update\"}[$__rate_interval])",
     "legendFormat": "Update Operation Rate"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\",command=\"delete\"}[$__rate_interval])",
     "legendFormat": "Delete Operation Rate"
    }
   ]
  },
  {
   "title": "MySQL throughput (msg/s)",
   "type": "stat",
   "description": "MySQL command performed (insert, update, delete)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rate(mysql_global_status_commands_total{job=\"mysql\",command=\"select\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Read Operation Rate"
    },
    {
     "expr": "avg_over_time(rate(mysql_global_status_commands_total{job=\"mysql\",command=\"insert\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Insert Operation Rate"
    },
    {
     "expr": "avg_over_time(rate(mysql_global_status_commands_total{job=\"mysql\",command=\"update\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Update Operation Rate"
    },
    {
     "expr": "avg_over_time(rate(mysql_global_status_commands_total{job=\"mysql\",command=\"delete\"}[$__rate_interval])[$__range:])",
     "legendFormat": "Delete Operation Rate"
    }
   ]
  },
  {
   "title": "MySQL throughput (msg/s)",
   "type": "stat",
   "description": "MySQL command performed (insert, update, delete)",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(rate(mysql_global_status_commands_total{job=\"mysql\",command=~\"delete|update|insert|select\"}[$__rate_interval])[$__range:]))",
     "legendFormat": "Total number of events"
    }
   ]
  },
  {
   "title": "MySQL bottlenecks",
   "type": "timeseries",
   "description": "Show MySQL bottlenecks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{job=\"mysql\"}[$__rate_interval])",
     "legendFormat": "Slow Queries Rate"
    }
   ]
  },
  {
   "title": "Send failures/errors",
   "type": "timeseries",
   "description": "Track if any messages are being dropped.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_metrics_record_error{job=\"debezium\"}[$__rate_interval]))\n",
     "legendFormat": "Error sumatory"
    }
   ]
  }
 ]
}