global:
  scrape_interval: 3s
  scrape_timeout: 2s  

scrape_configs:
  - job_name: 'database'
    static_configs:
      - targets: ['<debezium_machine_ip>:7073']
  - job_name: 'debezium'
    static_configs:
      - targets: ['<debezium_machine_ip>:7074']

