services:

  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    networks:
      - debezium
    healthcheck:
      test: /kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60